### ISSUE TITLE
Figure out why game freezes when joining servers

### ISSUE THREAD

**Issue by jacany** [Fallen-Networks/ModerationToolbox#7]
For some reason, the Client locks up on a black screen when joining the game server. It needs to be determined if this is a SCP:SL issue, or a plugin issue.

**Comment by jacany** [comment]
I suspect that it may be a plugin issue. Some sort of error when the player joins the game ends up hanging the entire join process. Therefore crashing the game.

**Comment by jacany** [comment]
We should use MEC Coroutines instead of timers, especially at **[ModerationToolbox/Common/Timer.cs](https://github.com/Fallen-Networks/ModerationToolbox/blob/master/ModerationToolbox/Common/Timer.cs)**. According to official EXILED documentation, it allows for sleeping without pausing execution on the main thread. This could definitely help out with our lag issue.

**Comment by jacany** [comment]
@hydrogen-fn you're better at this. you have any idea what could be going on? could my methods in Player.cs be pausing the main thread? would making a new thread prevent it from pausing it?

**Comment by hydrogen-fn** [comment]
> @hydrogen-fn you're better at this. you have any idea what could be going on? could my methods in Player.cs be pausing the main thread? would making a new thread prevent it from pausing it?

I believe it could quite possibly be Player.cs spiking lag to the client, creating another thread to handle some workload (and fix and 'pausing' issues) would be a possible solution. Multi-threading is a bless from the heavens.

**Comment by jacany** [comment]
> > @hydrogen-fn you're better at this. you have any idea what could be going on? could my methods in Player.cs be pausing the main thread? would making a new thread prevent it from pausing it?
> 
> I believe it could quite possibly be Player.cs spiking lag to the client, creating another thread to handle some workload (and fix and 'pausing' issues) would be a possible solution. Multi-threading is a bless from the heavens.

![image](https://user-images.githubusercontent.com/30955604/109181027-7d205e00-7759-11eb-9641-6b1bc0035c9e.png)
As you can see, the multithreading solution will probably work perfectly. As you can see, it prints `Based!` before the child thread does it's thing. Whether this works asynchronously is another question, but I don't see why it wouldn't work.

**Comment by jacany** [comment]
I will be doing some tests later. For example, i will just sleep for 10 seconds on Player.cs, and see if it takes 10 seconds to join. Then I will find the average time with the normal methods. After that, i will be testing the time without any methods in **[Verified](https://github.com/Fallen-Networks/ModerationToolbox/blob/multithreading/ModerationToolbox/Handlers/Player.cs#L9)**. After that I will be trying the same thing with multithreading, and then seeing if it is faster when joining the server with the normal functions.

**Comment by hydrogen-fn** [comment]
> > > @hydrogen-fn you're better at this. you have any idea what could be going on? could my methods in Player.cs be pausing the main thread? would making a new thread prevent it from pausing it?
> > 
> > 
> > I believe it could quite possibly be Player.cs spiking lag to the client, creating another thread to handle some workload (and fix and 'pausing' issues) would be a possible solution. Multi-threading is a bless from the heavens.
> 
> ![image](https://user-images.githubusercontent.com/30955604/109181027-7d205e00-7759-11eb-9641-6b1bc0035c9e.png)
> As you can see, the multithreading solution will probably work perfectly. As you can see, it prints `Based!` before the child thread does it's thing. Whether this works asynchronously is another question, but I don't see why it wouldn't work.

well, I would hope multi-threading would work asynchronously :open_mouth:

either way... in a theoretical situation, your problem should be fixed.

**Comment by jacany** [comment]
https://user-images.githubusercontent.com/30955604/109200833-0d1cd280-776f-11eb-9040-3c2c168e8971.mp4
Well, it appears that my suspicion was correct. The _Verified_ event runs synchronously on the main thread.
```c#
Log.Info("Starting timeout");
Thread.Sleep(10000);
Log.Info("Done lol");
```
That was my code, quite simple.

**Comment by jacany** [comment]
The _Verified_ does actually run on the main thread. So the solution should be easy.

```c#
Log.Info("Starting timeout");
Thread.Sleep(10000);
Log.Info("Done lol");
```
